---
identifier_name:
  allowed_symbols:
    - "_"
  excluded:
    - "id"
    - "TP"
    - "IP"
    - "MP"
    - "up"

disabled_rules:
  - nesting  # Opinion-based (https://stackoverflow.com/a/46767132/584548)
  - non_optional_string_data_conversion # Debatable (https://github.com/realm/SwiftLint/issues/5263)
